-- 0005_vec_index: sqlite-vec foundation (PR-67a).
--
-- Round 66 baseline locked in `search_chunks_vec` at O(N) full-scan +
-- Rust-side cosine. PR-67a moves that work into sqlite-vec's bundled C
-- (`vec0` virtual table), preserves the BLOB column as source-of-truth
-- + fallback, and lets `SearchFilter` predicates apply *inside* the
-- KNN scan via vec0 metadata columns / partition key — which is what
-- prevents the minority-adapter empty-result regression noted in
-- `search_chunks_vec`.
--
-- Why this migration is mostly bookkeeping:
-- The vec0 virtual-table DDL has the embedding dimension baked into
-- the schema (`float[N]`). We support arbitrary `(model_id, dim)`
-- combos at runtime, so we can't enumerate the tables up-front in pure
-- SQL — they have to be generated by Rust on `Store::open` from the
-- distinct dims observed in `chunk_embeddings`.
--
-- This migration therefore:
--   1. Creates a registry (`chunk_vec_indexes`) so the open path knows
--      which per-dim tables already exist.
--   2. Sets a one-shot `chunk_vec_index_backfill_pending` flag in
--      `meta` so `Store::open` knows to populate vec0 from the existing
--      BLOB rows the first time the new binary touches an old DB.

-- Pre-existing rows from v1/v2 stores had `instance` allowed to be
-- NULL before the v3 path normalised None → ''. The vec0 backfill
-- filter joins on `r.instance` and treats NULL as a non-match, so we
-- normalise once here for consistency with the live write path.
UPDATE records SET instance = '' WHERE instance IS NULL;

CREATE TABLE IF NOT EXISTS chunk_vec_indexes (
    dim        INTEGER PRIMARY KEY,
    table_name TEXT    NOT NULL UNIQUE,
    built_at   INTEGER NOT NULL
);

INSERT OR REPLACE INTO meta(key, value)
VALUES ('chunk_vec_index_backfill_pending', '1');

UPDATE meta SET value = '4' WHERE key = 'schema_version';
